/* Network adapter: presentation state only; never ticks or mutates the server simulation. */
const HexDuoClient=(()=>{
 function presentation(view,old){return {...view,boards:view.boards.map((board,i)=>{const previous=old?.boards[i]?.state;return {state:{...board,remoteView:true,showSlotHints:true,duoPortal:view.portals[i],selectedSlot:previous?.selectedSlot,selectedTower:previous?.selectedTower,selectedBuilding:previous?.selectedBuilding,hp:view.hp,maxHp:view.maxHp,hand:board.hand||[],deck:Object.entries(board.deckCounts||{}).flatMap(([id,n])=>Array(n).fill(id)),map:new Map(board.map.map(t=>[t.q+','+t.r,t])),landmarks:new Map(board.landmarks.map(t=>[t.q+','+t.r,t])),towerLoadout:board.loadout||[],ultimateUnlocks:board.ultimateUnlocks||[],buildingUnlocks:board.buildingUnlocks||[],waveRunning:board.phase==='wave',celebrationActive:!!board.celebration,activeCelebration:board.celebration,projectiles:board.projectiles||[],selectedCard:old?.wave===view.wave&&previous?.phase===board.phase&&previous?.hand?.join('|')===board.hand?.join('|')?(previous?.selectedCard??-1):-1,rotation:previous?.rotation||0,hoveredPlacement:previous?.hoveredPlacement}};})};}
 function create({token,fetchImpl=fetch,onView=()=>{},onStatus=()=>{},clientId=crypto.randomUUID(),ioFactory=globalThis.io}){
  const socket=typeof ioFactory==='function'?ioFactory({autoConnect:false,auth:{token,clientId},reconnection:true}):null;
  let view=null,busy=false,stopped=false,offline=false,conflict=false,timer;
  async function request(path,packet){if(socket){if(!socket.connected)throw Error('Verbindung wird wiederhergestellt …');const response=await socket.timeout(5000).emitWithAck('request',{path,packet});if(response.status!==200){const error=Error('Verbindung fehlgeschlagen ('+response.status+').');error.reason=response.body.error;if(error.reason==='session-replaced'){conflict=true;error.message='Diese Sitzung ist in einem anderen Tab geöffnet.';}throw error;}return response.body;}const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetchImpl(path,{method:packet?'POST':'GET',headers:{Authorization:'Bearer '+token,'X-Duo-Client':clientId,...(packet?{'Content-Type':'application/json'}:{})},...(packet?{body:JSON.stringify(packet)}:{}),signal:controller.signal});if(!response.ok){const error=Error('Verbindung fehlgeschlagen ('+response.status+').');try{error.reason=(await response.json()).error;}catch{}if(error.reason==='session-replaced'){conflict=true;error.message='Diese Sitzung ist in einem anderen Tab geöffnet.';}throw error;}return await response.json();}finally{clearTimeout(timeout);}}
  async function refresh(){const next=await request('/state');if(next.protocol!==1)throw Error('Unpassende Serverversion.');if(!view||view.serverId!==next.serverId||view.epoch!==next.epoch||(next.revision>view.revision||next.revision===view.revision&&next.next>=view.next)){view=next;onView(view);}conflict=false;return view;}
  async function send(action,payload={}){if(conflict)throw Error('Sitzung zuerst in diesem Tab übernehmen.');if(offline||view?.connection?.paused)throw Error(view?.connection?.expired?'Wiederbeitrittsfenster abgelaufen · Bitte eine neue Lobby erstellen.':'Verbindung unterbrochen. Wiederverbinden läuft …');if(busy||!view)throw Error('Bitte auf die Serverbestätigung warten.');busy=true;const packet={epoch:view.epoch,sequence:view.next,wave:view.wave,phase:view.boards[view.player].phase,action,payload};try{let result;for(let attempt=0;attempt<2;attempt++){try{result=await request('/command',packet);break;}catch(error){if(attempt)throw error;}}await refresh();if(!result.ok)throw Error('Aktion abgelehnt: '+result.reason);return result;}finally{busy=false;}}
  async function poll(){if(stopped)return;try{if(!busy){await refresh();offline=false;const c=view.connection;onStatus(c?.maintenance?'Serverwartung · Partie sicher pausiert. Bitte warten.':c?.ended?'Die Partie wurde von einem Spieler verlassen. Zurück zur Lobby.':c?.expired?'Wiederbeitrittsfenster abgelaufen · Bitte eine neue Lobby erstellen.':c?.paused?'Partnerverbindung unterbrochen · Partie pausiert · Rückkehrfenster: '+c.remainingSeconds+' s':'Verbunden · Server steuert den Run',{conflict:false,ended:!!c?.ended});}}catch(error){offline=true;onStatus(error.message+(conflict?' Du kannst sie hier ausdrücklich übernehmen.':' Neuer Versuch läuft …'),{conflict});}finally{if(!stopped)timer=setTimeout(poll,offline?1000:100);}}
  async function session(action){if(busy)throw Error('Bitte auf die Serverbestätigung warten.');busy=true;try{let result;for(let attempt=0;attempt<2;attempt++){try{result=await request('/session',{action});break;}catch(error){if(attempt||error.reason==='session-replaced')throw error;}}if(!result.ok)throw Error('Sitzungsaktion abgelehnt.');if(action==='takeover'){conflict=false;offline=false;await refresh();onStatus('Sitzung in diesem Tab übernommen.',{conflict:false});}else{stopped=true;clearTimeout(timer);socket?.disconnect();}return result;}finally{busy=false;}}
  return {send,takeover:()=>session('takeover'),leave:()=>session('leave'),start(){stopped=false;socket?.connect();poll();},stop(){stopped=true;clearTimeout(timer);socket?.disconnect();},get player(){return view?.player;},get busy(){return busy;}};
 }
 return {create,presentation};
})();
if(typeof module!=='undefined')module.exports=HexDuoClient;
