const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const {prepare}=require('../release-notes.cjs');
test('release notes are required, versioned once, keep history and do not mutate files during validation',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'autohex-notes-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'notes.json'),entries=[{version:'next',title:'Test',changes:['Eine Änderung']},{version:'0.9.5',title:'Alt',changes:['Alt']}];fs.writeFileSync(file,JSON.stringify(entries));const notes=prepare(file,'0.9.6','2026-10-08');assert.equal(notes[0].version,'0.9.6');assert.equal(notes[0].date,'2026-10-08');assert.equal(notes[1].version,'0.9.5');assert.equal(JSON.parse(fs.readFileSync(file))[0].version,'next');assert.throws(()=>prepare(file,'0.9.5'));fs.writeFileSync(file,JSON.stringify(notes));assert.throws(()=>prepare(file,'0.9.7'),/Patch Notes fehlen/);
});
test('patch notes render text safely and Escape closes without an outside-click dismiss',async()=>{
 const nodes=new Map(),listeners={};function node(){return {children:[],textContent:'',classList:{hidden:true,add(){this.hidden=true;},remove(){this.hidden=false;},contains(){return this.hidden;}},events:{},addEventListener(n,f){this.events[n]=f;},appendChild(n){this.children.push(n);},replaceChildren(){this.children=[];}};}
 const context={document:{getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},createElement:node,addEventListener:(name,fn)=>listeners[name]=fn},fetch:async()=>({ok:true,json:async()=>[{version:'next',title:'Test',changes:['<script>never run</script>']}]})};vm.runInNewContext(fs.readFileSync('classes/patch-notes.js','utf8'),context);await nodes.get('menuPatchNotesBtn').events.click();assert.equal(nodes.get('patchNotesContent').children[0].children[2].children[0].textContent,'<script>never run</script>');assert.equal(nodes.get('patchNotesOverlay').classList.hidden,false);assert.equal(nodes.get('patchNotesOverlay').events.click,undefined);listeners.keydown({key:'Escape',preventDefault(){},stopImmediatePropagation(){}});assert.equal(nodes.get('patchNotesOverlay').classList.hidden,true);
});
