/* A portable result card. Sharing is initiated only by the player's click. */
const HexRunShare=(()=>{
  const number=n=>Math.max(0,Math.floor(Number(n)||0));
  function summary(state){return {wave:number(state.lastCompletedWave??Math.max(0,(state.wave||0)-(state.phase==='gameover'?1:0))),gold:Object.values(state.goldEarned||{}).reduce((n,v)=>n+number(v),0),kills:Object.values(state.runTowerStats||{}).reduce((n,t)=>n+number(t.kills),0)+number(state.baseKills)+number(state.consumableKills),mode:state.duoMode?'Duo':state.challengeDay?(state.challengeKind==='garrison'?'Die letzte Garnison':'Tägliche Herausforderung'):state.difficulty==='dual'?'Zwei Fronten':'Standard'};}
  const fmt=n=>n.toLocaleString('de-DE');
  function markup(state){const s=summary(state);return '<section class="runShareCard"><div class="runShareBrand">AUTOHEX TD · '+s.mode+'</div><div class="runShareWave">Welle '+s.wave+'</div><p>vollständig überlebt</p><div class="runShareMetrics"><span><strong>'+fmt(s.gold)+'</strong> Gold verdient</span><span><strong>'+fmt(s.kills)+'</strong> Kills</span></div><small>Gold ohne Startkapital und Verkaufserstattungen · Kills eigener Türme, Basis und Verbrauchshilfen</small><div class="runShareActions"><button data-run-share="copy">Bild kopieren</button><button data-run-share="share">Teilen …</button><button data-run-share="download">PNG herunterladen</button></div><p class="runShareStatus" role="status" aria-live="polite"></p></section>';}
  function image(state){const s=summary(state),canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const c=canvas.getContext('2d');c.fillStyle='#14251f';c.fillRect(0,0,1200,630);c.strokeStyle='#d9bc76';c.lineWidth=3;c.strokeRect(25,25,1150,580);c.fillStyle='#d9bc76';c.font='bold 28px sans-serif';c.fillText('AUTOHEX TD',70,90);c.fillStyle='#f2e7cf';c.font='24px sans-serif';c.fillText(s.mode,70,140);c.font='bold 110px sans-serif';c.fillText('Welle '+s.wave,65,285);c.font='30px sans-serif';c.fillText('vollständig überlebt',70,335);c.font='bold 48px sans-serif';c.fillText(fmt(s.gold)+' Gold',70,435);c.fillText(fmt(s.kills)+' Kills',670,435);c.font='23px sans-serif';c.fillText('im Durchlauf verdient',70,474);c.fillText('Türme, Basis und Verbrauchshilfen',670,474);c.fillStyle='#b3c0b5';c.font='20px sans-serif';c.fillText('autohextd.zlyfer.net',70,566);return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Bild konnte nicht erstellt werden.')),'image/png'));}
  function download(blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='autohex-td-ergebnis.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  function install(getState){document.addEventListener('click',async event=>{const button=event.target.closest?.('[data-run-share]');if(!button||!['copy','share','download'].includes(button.dataset?.runShare))return;const box=button.closest('.runShareCard'),status=box.querySelector('.runShareStatus'),action=button.dataset.runShare,state=getState();button.disabled=true;try{
      // Pass the promise immediately to preserve transient clipboard activation.
      const blobPromise=image(state);
      if(action==='copy'&&globalThis.ClipboardItem&&navigator.clipboard?.write){try{await navigator.clipboard.write([new ClipboardItem({'image/png':blobPromise})]);status.textContent='Ergebnisbild kopiert.';return;}catch{download(await blobPromise);status.textContent='Kopieren nicht verfügbar. Das PNG wurde heruntergeladen.';return;}}
      const blob=await blobPromise,file=new File([blob],'autohex-td-ergebnis.png',{type:'image/png'});
      if(action==='share'&&navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({title:'Mein AutoHex-TD-Ergebnis',files:[file]});status.textContent='Teildialog geschlossen.';}
      else{download(blob);status.textContent=action==='download'?'PNG heruntergeladen.':'Teilen hier nicht verfügbar. PNG herunterladen und in der gewünschten App teilen.';}
    }catch(error){status.textContent=error.name==='AbortError'?'Teilen abgebrochen.':'Das Ergebnisbild konnte nicht exportiert werden. Bitte erneut versuchen.';}finally{button.disabled=false;}});}
  return {summary,markup,image,install};
})();
if(typeof module!=='undefined')module.exports=HexRunShare;
