const {test}=require('node:test'),assert=require('node:assert/strict'),{load}=require('./helpers/game.cjs'),loadCore=require('../headless-core.cjs');
function finish35(a){a.state.wave=35;a.state.waveRunning=true;a.state.phase='wave';a.state.enemies=[];a.state.pendingSpawns=0;a.state.spawnQueue=[];a.endWave();}
test('dual is locked until normal wave 35 is completed; endless keeps run and settles only at its end',()=>{
 const {a,elements,storage}=load();elements.get('newRunBtn').listeners.click();assert.equal(elements.get('difficultyChoices').children[1].disabled,true);a.newRun(undefined,undefined,'dual');assert.equal(a.state.difficulty,'normal');const id=a.state.runId;finish35(a);assert.equal(a.state.phase,'victory');assert.equal(a.state.metaSettled,false);assert.ok(JSON.parse(storage.get('hex-bastion-profile-v1')).milestones.includes('standard35'));const checkpoint=a.captureRunCheckpoint();a.restoreRunCheckpoint(checkpoint);assert.equal(a.state.phase,'victory');elements.get('endlessBtn').listeners.click();assert.equal(a.state.endless,true);assert.equal(a.state.runId,id);assert.notEqual(a.state.phase,'victory');assert.equal(a.state.metaSettled,false);a.newRun(undefined,undefined,'dual');assert.equal(a.state.difficulty,'dual');
});
test('victory main menu pays once and failed wave 35 never unlocks difficulty',()=>{
 const {a,elements,storage}=load();a.state.wave=35;a.state.hp=0;a.endWave();assert.equal(storage.get('hex-bastion-profile-v1'),undefined);a.newRun();finish35(a);elements.get('victoryMenuBtn').listeners.click();const profile=storage.get('hex-bastion-profile-v1');elements.get('victoryMenuBtn').listeners.click();assert.equal(storage.get('hex-bastion-profile-v1'),profile);assert.equal(a.state.metaSettled,true);assert.equal(a.state.phase,'gameover');
});
test('boss roster differentiates armor, speed and magic; summons are bounded and checkpoint safe',()=>{
 const c=loadCore(),iron=c.waves.bossProfile(15),hunter=c.waves.bossProfile(25),queen=c.waves.bossProfile(35);assert.ok(iron.armorHp/iron.hp>hunter.armorHp/hunter.hp);assert.ok(hunter.speed>iron.speed*1.5);assert.ok(queen.magicHp/queen.hp>iron.magicHp/iron.hp);
 const run=c.session.create({seed:'summon',runId:'summon',loadout:['archer','catapult','chain','freeze','mine']}),s=run.state;s.phase='wave';s.wave=35;s.waveRunning=true;s.spawnQueue=[];s.pendingSpawns=0;s.enemies=[{...queen,id:s.nextEnemyId++,speed:0,maxHp:queen.hp,alive:true,points:[{x:10000,y:0},{x:20000,y:0}],x:10000,y:0,index:0,t:0}];
 for(let i=0;i<140;i++)c.runtime.advance(s,run.random,.05);assert.equal(s.enemies.filter(e=>e.summoned===true).length,1);const restored=c.snapshot.restore(JSON.parse(JSON.stringify(c.snapshot.capture(s,run.random))));for(let i=0;i<1000;i++){c.runtime.advance(s,run.random,.05);c.runtime.advance(restored.state,restored.random,.05);}assert.equal(s.enemies.filter(e=>e.summoned===true).length,6);assert.ok(s.enemies.filter(e=>e.summoned===true).every(e=>e.killGold===0));assert.deepEqual(JSON.parse(JSON.stringify(c.snapshot.capture(s,run.random))),JSON.parse(JSON.stringify(c.snapshot.capture(restored.state,restored.random))));
});
