const fs = require('node:fs'), vm = require('node:vm'), path = require('node:path');
const classesDir = path.join(__dirname, '../../classes');
function load({ duo = null, now = () => 0, headless = false, initialProfile = null, initialStorage = {}, rotateView = null, pickSlot = null, project = null, boardBox = null, getRenderedFrameCount = null, accountApi = null } = {}) {
  const elements = new Map();
  function element() { const classes = new Set(); return { textContent: '', get innerHTML() { return this.html || ''; }, set innerHTML(value) { this.html = value; this.children = []; }, style: {}, dataset: {}, replaceChildren(...items){this.children=items;}, children: [], attributes: {}, listeners: {}, captureListeners: {}, classList: { add(...names) { names.forEach(n => classes.add(n)); }, remove(...names) { names.forEach(n => classes.delete(n)); }, contains(n) { return classes.has(n); }, toggle(n, force) { const on = force ?? !classes.has(n); if (on) classes.add(n); else classes.delete(n); return on; } }, setAttribute(name, value) { this.attributes[name] = value; }, addEventListener(name, fn, capture) { (capture === true ? this.captureListeners : this.listeners)[name] = fn; }, appendChild(e) { this.children.push(e); } }; }
  const timers = new Map(); let next = 1;
  const storage = new Map(Object.entries({ 'tutorial-v1': 'done', ...initialStorage })); if (initialProfile) storage.set('hex-bastion-profile-v1', JSON.stringify(initialProfile)); const documentListeners = {}, globalListeners = {};
  const context = { addEventListener(name, fn) { globalListeners[name] = fn; }, document: { querySelectorAll(){return [];}, getElementById(id) { if (!elements.has(id)) elements.set(id, element()); return elements.get(id); }, createElement: element, createElementNS: element, addEventListener(name, fn) { const previous=documentListeners[name]; documentListeners[name]=previous?event=>{previous(event);fn(event);}:fn; } }, localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, String(value)) }, performance: { now }, requestAnimationFrame() { }, setTimeout(fn) { const id = next++; timers.set(id, fn); return id; }, clearTimeout(id) { timers.delete(id); }, Math };
  if(duo){context.URLSearchParams=URLSearchParams;context.location={hash:'#duo=test-token',assign(){},replace(){}};context.document.body=element();context.HexDuoGame={mount(api){duo.api=api;return duo;}};}
  if(duo?.real){context.document.querySelector=selector=>selector==='.dockTL'?context.document.getElementById('testDock'):null;context.sessionStorage=context.localStorage;context.crypto={randomUUID:()=> '11111111-1111-1111-1111-111111111111'};context.HexDuoClient={presentation:require('../../duo-client.js').presentation,create(options){duo.receive=options.onView;return {start(){},stop(){},async send(action,payload){duo.calls.push({action,payload});},async leave(){},async takeover(){}};}};vm.runInNewContext(fs.readFileSync(path.join(classesDir,'duo-game.js'),'utf8').replace('const HexDuoGame=','globalThis.HexDuoGame='),context);const mount=context.HexDuoGame.mount;context.HexDuoGame.mount=api=>{duo.api=api;duo.bridge=mount(api);return duo.bridge;};}
  if (boardBox) context.document.querySelector = selector => selector === '.boardWrap' ? { getBoundingClientRect: () => boardBox } : null;
  context.document.getElementById('saveOverlay').classList.add('hidden');
  context.document.getElementById('accountOverlay').classList.add('hidden');
  if (accountApi) context.HexApi = accountApi;
  let source = fs.readFileSync(path.join(classesDir, 'game.js'), 'utf8');
  if (headless) source = source.replace('renderBoard(); renderUI();', '');
  for (const file of ['run-share.js', 'biomes.js', 'data.js', 'ui-layout.js', 'tutorial.js', 'heroes.js', 'profile.js', 'map.js', 'random.js', 'run-runtime.js', 'run-snapshot.js', 'waves.js', 'combat.js', 'rewards.js', 'deck.js', 'buildings.js', 'tower-commands.js', 'exploration.js', 'placement-commands.js', 'run-flow.js', 'run-session.js', 'camera.js', 'svg-renderer.js', 'arsenal.js']) vm.runInNewContext(fs.readFileSync(path.join(classesDir, file), 'utf8'), context);
  if (rotateView || pickSlot || project || getRenderedFrameCount) { const svgRenderer = vm.runInNewContext('HexSvgRenderer', context); context.HexThreeRenderer = { create: (...args) => ({ ...svgRenderer.create(...args), rotateView, ...(getRenderedFrameCount ? { getRenderedFrameCount } : {}), ...(pickSlot ? { pickSlot } : {}), ...(project ? { project } : {}) }) }; }
  source = source.replace('duoBridge=HexDuoGame.mount({','globalThis.testRendererCommands=rendererCommands;duoBridge=HexDuoGame.mount({');
  source = source.replace('newRun(); hasActiveRun=false; openMainMenu(); requestAnimationFrame(frame);', 'newRun(); globalThis.api={get state(){return state;},rendererCommands,layoutMenus,renderRunStatistics,newRun,captureRunCheckpoint,restoreRunCheckpoint,updateFps,advanceClock,advanceCamera,canPlace,rotatedRoads,neighbor,edgePoint,axialToPixel:axialToWorld,buildGraph,pathToBase,spawnSources,startWave,update,drawHand,showRewards,showRemoval,placeTile,finishRemoval,renderAll,endWave,showBossReward,finishBossReward,CARD_LIBRARY};');
  vm.runInNewContext(source.replace('newRun(); globalThis.api=', 'newRun(); globalThis.upgradeSelectedTower=upgradeSelectedTower;globalThis.selectSlot=selectSlot;globalThis.sellSelectedTower=sellSelectedTower;globalThis.buyTower=buyTower;globalThis.slotPositions=slotPositions; globalThis.nextSourcePoints=nextSourcePoints; globalThis.api='), context);
  return { rendererCommands:context.testRendererCommands, buildings: vm.runInNewContext("HexBuildings", context), data: vm.runInNewContext("HexData", context), waves: vm.runInNewContext("HexWaves", context), a: context.api, upgradeSelectedTower: context.upgradeSelectedTower, selectSlot: context.selectSlot, buyTower: context.buyTower, sellSelectedTower: context.sellSelectedTower, slotPositions: context.slotPositions, nextSourcePoints: context.nextSourcePoints, timers, elements, storage, documentListeners, globalListeners, document:context.document };
}


module.exports = { load };


